---
title: "Mapa del índice de diferencia normalizada de edificación (NDBI) de la Gran Área Metropolitana"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leaflet.opacity)
library(leafem)
library(esri2sf)
library(raster)

#--------------- URL de geoservicios --------------

url_agfs_limite_gam <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_gam/FeatureServer/0"

url_raster_ndbi <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-calentamiento-urbano/master/gam/NBDI_GAM_WEB.TIF"

#--------------- Objetos sf y raster ---------------

# Límite de la GAM
sf_limite_gam <-
  esri2sf(url_agfs_limite_gam)

# Límite de la GAM (reproyectado a Web Mercator)
sf_limite_gam_web <- 
  sf_limite_gam %>%
  st_transform(3857)

# Capa raster de NDBI (en Web Mercator)
raster_ndbi <-
  raster(url_raster_ndbi) %>%
  aggregate(fact=2, fun=modal) %>% # ¡¡HAY QUE TRATAR DE ELIMINAR ESTA AGRUPACIÓN. PODRÍA FUNCIONAR AL USAR MÁS MEMORIA LINUX!!  
  crop(sf_limite_gam_web) %>%
  mask(sf_limite_gam_web)

raster_ndbi[raster_ndbi==65535] <- NA
min_raster_ndbi <- format(cellStats(raster_ndbi, stat='min'), digits=2, nsmall=1)
max_raster_ndbi <- format(cellStats(raster_ndbi, stat='max'), digits=2, nsmall=1)
mean_raster_ndbi <- format(cellStats(raster_ndbi, stat='mean'), digits=2, nsmall=1)

#---------------- Paletas de colores ---------------

# NDBI
colores_ndbi <- "Greys"
pal_ndbi <- 
  colorNumeric(
    colores_ndbi, 
    values(raster_ndbi),
    na.color = "transparent"
  )

```

Row {data-height=800}
-----------------------------------------------------------------------

### 

```{r}

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%  
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_gam,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite de la GAM"
  ) %>%
  addRasterImage(
    raster_ndbi, 
    layerId = "raster",    
    colors = pal_ndbi,
    opacity = 0.9,
    group = "NDBI"
  ) %>%  
  addLegend(
    title = "NDBI",
    values = values(raster_ndbi),
    pal = pal_ndbi,
    position = "bottomright",
    group = "NDBI"
  ) %>%    
  addLayersControl(
    baseGroups = c("OpenStreetMap", "CartoDB Dark Matter", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Límite de la GAM", "NDBI"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates() %>%
  addSearchOSM() %>%
  addResetMapButton() %>%
  addOpacitySlider(layerId = "raster")
```

Row {data-height=200}
-----------------------------------------------------------------------

### NDBI mínimo {.value-box} {data-width=333}
```{r}
valueBox(
  value = "NDBI mínimo", 
  caption = paste("<h2><strong>", min_raster_ndbi,  "</strong></h2>")
)
```

### NDBI máximo {.value-box} {data-width=333}
```{r}
valueBox(
  value = "NDBI máximo", 
  caption = paste("<h2><strong>", max_raster_ndbi,  "</strong></h2>")
)
```

### NDBI promedio {.value-box} {data-width=333}
```{r}
valueBox(
  value = "NDBI promedio", 
  caption = paste("<h2><strong>", mean_raster_ndbi,  "</strong></h2>")
)
```